### ISSUE TITLE
The effect of RandomProject from 128 to 256 in OGB-MAG dataset

### ISSUE THREAD

**Issue by Adam1679** [facebookresearch/NARS#1]
Dear Authors,

It is amazing to see such works that eliminate the necessity of GNN-like structure to achieve the state-of-the-art.

I have a question on the featureless node embedding. On OGB-MAG dataset, you used TransE to embed the featureless into 256d vector while the original feature dimension is 128d. And then you use random projection to project 128d to 256d. I don't quite understand such an operation. Why not set embedding dimension as 128 in the first place?

**Comment by lingfanyu** [comment]
Hi @Adam1679 , thanks for your interest in our project.

In my opinion, the embedding size of TransE should be selected based on the size of graph (i.e. # nodes, # edges) instead of the input feature size of nodes. OGB-MAG graph is relatively large, and we found that using TransE size 256 produces slightly better results than 128. 

And in the other cases that each node comes with a large input feature, for example 2048-dimensional, we might also want to use a different (and smaller) TransE size if the graph size is not that huge.  We always project the one with smaller dimension to larger dimension with a random projection, and hopefully all information will be kept.

**Comment by Adam1679** [comment]
Thanks for your explaination. 

Do you have any reference that using random projection is better than padding zeros?

**Comment by lingfanyu** [comment]
Actually I don't have reference about that. And I have never experimented with padding zeros, so I am not sure how that would affect the performance.
