### ISSUE TITLE
The mismatch of paper nodes in OAG dataset.

### ISSUE THREAD

**Issue by hcmdgh** [facebookresearch/NARS#10]
Dear authors, we download the OAG dataset file graph_CS.pk as illustrated in your README. However, when we load the dataset, the total number of papers is 544244, but in your paper it says 5,597,605. Why does it hava a 10x difference?

**Comment by lingfanyu** [comment]
Hi @hcmdgh 

We simply used the preprocessed OAG dataset from HGT paper in order to compare against their approach. In fact, in the footnote of page 12 (Appendix A.3) of our paper, we actually mentioned the 10x difference:

> HGT authors only shared the CS component. Also, they performed a filter step to make the graph denser. After the filtering, there are 544244 papers ,45717 fields, 510189 authors, 9079 institutes, and 6933 venues left.

You can raise an issue at HGT Github repository (https://github.com/acbull/pyHGT#oag-dataset) for further explanation.

Thanks!

**Comment by hcmdgh** [comment]
Thanks a lot.
