### ISSUE TITLE
Out of gpu memory

### ISSUE THREAD

**Issue by BlackHorseQ** [facebookresearch/NARS#2]
hi,
I have a question about gpu memory. When I use MAG dataset, I found the number of hop of neighbors R is seated as 6. But I use Teslav100(32g), It is out of gpu memory. I calculate the size of one neighbor feature, and the size is 6 gb, according to your article, just use a tesla v100, I do not think this can be achieved.
I am sorry if I ignore anything that can deal with the issue

**Comment by lingfanyu** [comment]
Hi @BlackHorseQ ,

Did you get the out-of-memory error in the preprocessing step when NARS is computing R hop features for paper nodes, or in the training phase when they MLP classifier is being trained?

Also, could you share how you computed that neighbor feature size is 6 gb?

For the MAG dataset, we used R=5 (instead of 6) and the preprocessing step and mini-batch training both fit in V100 (16GB).

**Comment by BlackHorseQ** [comment]
Thank you for your reply.

**Comment by lingfanyu** [comment]
@BlackHorseQ 

The MAG dataset has 500k paper nodes (for prediction), and NARS needs to store neighbor-averaged features for R+1 hops (1 for the hop-0/self-feature). So the amount of memory needed is 500K * input_feature_size * (R+1) * sizeof(float) = 500K * 256 * 6 * 4 bytes = 3GB. And NARS needs to store features for each of the K relation subsets it samples. If no optimization is done, after preprocessing step, it would probably run out of GPU memory (say 16 GB)

To handle this problem, we simply compute the neighbor-averaged features on GPU and then move them to CPU memory to free up GPU space:
https://github.com/facebookresearch/NARS/blob/27850d3812e04d2057ba6b53aae02fd35a0e180c/data.py#L88

During the training phase, we do mini-batch training and will load the data that a batch needs back to GPU:
https://github.com/facebookresearch/NARS/blob/27850d3812e04d2057ba6b53aae02fd35a0e180c/utils.py#L31

By doing so, NARS (our pytorch version) can easily run with 16GB GPU memory. But the training process does slow down because we have to copy a batch of data to GPU during training phase. In our paper Figure 3, we actually have a dashed line showing the training time if GPU is large enough to store all the features so that no cpu to gpu copy is needed. We did this by saving part of the features in another GPU's memory (which is only used as extra storage), and when this part of data is needed, it's copied to the training GPU via NVLink which is much faster than PCIe.

**Comment by lingfanyu** [comment]
It looks like the problem might have been solved since there is no more follow-up. I'm closing the issue, but feel free to reopen it if you have more questions.

**Comment by BlackHorseQ** [comment]
> It looks like the problem might have been solved since there is no more follow-up. I'm closing the issue, but feel free to reopen it if you have more questions.

Thank you for your patient reply! I found paddlepaddle framework don't have the same attribute as pytorch.
