### ISSUE TITLE
question about sampled relation subsets

### ISSUE THREAD

**Issue by maqy1995** [facebookresearch/NARS#4]
Hi,
    I have a question about sampled relation subsets. 
    When using the mag dataset, `affiliated_with, has_topic` is one of the sampled relation subsets. Is the relation `affiliated_with` redundant to build the subgraph?  Because `author-affiliated_with-institution` and `institution-affiliated_with_r-author` has no effect on the k-hop feature of `paper`, right? 
    It may be that I have misunderstood something. Looking forward to your reply.

**Comment by lingfanyu** [comment]
Hi @maqy1995,

Your understanding is correct.

If the sampled relations form several disconnected components, then only the component that contains target node type (i.e. paper nodes for MAG) has effect on the features of target nodes.

In your MAG example, if only (paper, has_topic, topic), (author, affiliated_with, institution) are sampled, then it's equivalent to only sampling (paper, has_topic, topic), because the information in the other disconnected component (author, affiliated, institution) has no way to propagate to paper nodes.

In NARS, we did not explicitly disallow sampling equivalent relation subsets. But we do filter out sampled subsets that don't touch target nodes:
https://github.com/facebookresearch/NARS/blob/27850d3812e04d2057ba6b53aae02fd35a0e180c/sample_relation_subsets/sample_random_subsets.py#L91-L99

**Comment by maqy1995** [comment]
Get it. Thanks for your reply.
