### ISSUE TITLE
The problem of new_subgrah implementation

### ISSUE THREAD

**Issue by GooLiang** [facebookresearch/NARS#8]
Hello dear author, I read your Nars paper and it helped a lot. 
I have a question in the code implementation part  in data.py Line 48
new_edges[(dtype, etype + "_r", stype)] = (dst, src)
 it seems to do a bidirectional graph operation on the mag dataset. We all know that the mag dataset is a directed graph, what is the purpose of doing this?、
Best wishes!

**Comment by lingfanyu** [comment]
Hi @GooLiang 

This step is NOT making the graph undirected. Instead, it's adding a reverse relation type for each edge type in the graph. For example, edge `(author A write paper B)` is different from the added edge `(paper B write_r author A)`, because `write` and `write_r` are treated as different types. You can interpret `write_r` as "is written by".

The purpose of adding reverse relation edge type is to help propagate information, especially in the case where there is only a directed edge from author A to paper B but no edge backwards, because message passing only happens along the direction of the edge. Adding `write_r` edge makes it possible for author A to use feature of paper B.
